In [1]:
import numpy as np

# View

In [3]:
a = np.array([-2,-1,0,1,2,3])

In [4]:
b=a

In [5]:
a is b

True

In [6]:
id(a)

2582156993120

In [7]:
id(b)

2582156993120

In [8]:
a == b

array([ True,  True,  True,  True,  True,  True])

In [9]:
a[2] = 10

In [11]:
a == b ##If all TRUE, Means both a and b refer to same location

array([ True,  True,  True,  True,  True,  True])

In [15]:
c = a.view()  ##Coverting into view
c.shape = (3,2)  ##Changing the display sequence
c

array([[-2, -1],
       [10,  1],
       [ 2,  3]])

In [16]:
a[3] = -1000 

In [17]:
c  ##Means c and a are refering to the same location in memory

array([[   -2,    -1],
       [   10, -1000],
       [    2,     3]])

In [20]:
c is a ##False bcoz c is view of a

False

## Deep Copy

In [22]:
d = np.copy(a)  ##Means d is refering to different location then a; Just using its data to create d.
d[3] = 3333
d

array([  -2,   -1,   10, 3333,    2,    3])

In [23]:
a

array([   -2,    -1,    10, -1000,     2,     3])