# Joining and Splitting arrays
- concatenate
- stack
- split

In [1]:
import numpy as np

### concatenate
documentation: http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [25]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
together.shape

(3, 2)

In [5]:
together[1,1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [6]:
a

array([[1, 2],
       [3, 4]])

In [7]:
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [8]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

### stack

In [9]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[-0.78467762,  1.32248624, -1.1323359 , -0.25169093],
        [-0.5731287 , -0.09421838, -1.05027001,  1.69099116],
        [-0.56120506,  0.22738653, -1.55274232,  0.21077747]],

       [[-0.15728334,  0.35912015,  1.16314447, -0.80147272],
        [ 0.24506448,  1.63106248,  0.59188139,  0.42563135],
        [ 0.11760464, -0.34502434, -1.79845746, -0.61258559]],

       [[ 0.49825897,  1.56629224,  1.24126046,  1.8017724 ],
        [ 1.23196204, -0.18483868, -0.43542578, -0.21057927],
        [ 0.38108351, -0.31770294, -0.70599398, -0.17534895]],

       [[ 0.57591302,  0.87155863, -0.91698176, -0.17567884],
        [ 1.63177606, -1.69967738,  0.14885536, -0.21963932],
        [-1.96420029, -2.13787323, -1.16156957,  0.04414762]],

       [[-3.15064601,  1.57556994, -0.56142087, -0.34470738],
        [-0.36405664, -1.84629627, -0.07137769,  1.01912648],
        [-0.83439953, -2.08211233,  0.20557574, -0.83159375]]])

In [10]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [11]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

array([[5, 3, 4],
       [3, 5, 4],
       [3, 4, 5]])

In [12]:
stack0

array([[[-0.78467762,  1.32248624, -1.1323359 , -0.25169093],
        [-0.5731287 , -0.09421838, -1.05027001,  1.69099116],
        [-0.56120506,  0.22738653, -1.55274232,  0.21077747]],

       [[-0.15728334,  0.35912015,  1.16314447, -0.80147272],
        [ 0.24506448,  1.63106248,  0.59188139,  0.42563135],
        [ 0.11760464, -0.34502434, -1.79845746, -0.61258559]],

       [[ 0.49825897,  1.56629224,  1.24126046,  1.8017724 ],
        [ 1.23196204, -0.18483868, -0.43542578, -0.21057927],
        [ 0.38108351, -0.31770294, -0.70599398, -0.17534895]],

       [[ 0.57591302,  0.87155863, -0.91698176, -0.17567884],
        [ 1.63177606, -1.69967738,  0.14885536, -0.21963932],
        [-1.96420029, -2.13787323, -1.16156957,  0.04414762]],

       [[-3.15064601,  1.57556994, -0.56142087, -0.34470738],
        [-0.36405664, -1.84629627, -0.07137769,  1.01912648],
        [-0.83439953, -2.08211233,  0.20557574, -0.83159375]]])

In [13]:
stack1

array([[[-0.78467762,  1.32248624, -1.1323359 , -0.25169093],
        [-0.15728334,  0.35912015,  1.16314447, -0.80147272],
        [ 0.49825897,  1.56629224,  1.24126046,  1.8017724 ],
        [ 0.57591302,  0.87155863, -0.91698176, -0.17567884],
        [-3.15064601,  1.57556994, -0.56142087, -0.34470738]],

       [[-0.5731287 , -0.09421838, -1.05027001,  1.69099116],
        [ 0.24506448,  1.63106248,  0.59188139,  0.42563135],
        [ 1.23196204, -0.18483868, -0.43542578, -0.21057927],
        [ 1.63177606, -1.69967738,  0.14885536, -0.21963932],
        [-0.36405664, -1.84629627, -0.07137769,  1.01912648]],

       [[-0.56120506,  0.22738653, -1.55274232,  0.21077747],
        [ 0.11760464, -0.34502434, -1.79845746, -0.61258559],
        [ 0.38108351, -0.31770294, -0.70599398, -0.17534895],
        [-1.96420029, -2.13787323, -1.16156957,  0.04414762],
        [-0.83439953, -2.08211233,  0.20557574, -0.83159375]]])

In [14]:
stack2

array([[[-0.78467762, -0.15728334,  0.49825897,  0.57591302,
         -3.15064601],
        [ 1.32248624,  0.35912015,  1.56629224,  0.87155863,
          1.57556994],
        [-1.1323359 ,  1.16314447,  1.24126046, -0.91698176,
         -0.56142087],
        [-0.25169093, -0.80147272,  1.8017724 , -0.17567884,
         -0.34470738]],

       [[-0.5731287 ,  0.24506448,  1.23196204,  1.63177606,
         -0.36405664],
        [-0.09421838,  1.63106248, -0.18483868, -1.69967738,
         -1.84629627],
        [-1.05027001,  0.59188139, -0.43542578,  0.14885536,
         -0.07137769],
        [ 1.69099116,  0.42563135, -0.21057927, -0.21963932,
          1.01912648]],

       [[-0.56120506,  0.11760464,  0.38108351, -1.96420029,
         -0.83439953],
        [ 0.22738653, -0.34502434, -0.31770294, -2.13787323,
         -2.08211233],
        [-1.55274232, -1.79845746, -0.70599398, -1.16156957,
          0.20557574],
        [ 0.21077747, -0.61258559, -0.17534895,  0.04414762,
         -0

### split
for information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

In [15]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [16]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [17]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[-0.78467762,  1.32248624, -1.1323359 , -0.25169093],
         [-0.5731287 , -0.09421838, -1.05027001,  1.69099116],
         [-0.56120506,  0.22738653, -1.55274232,  0.21077747]]]),
 array([[[-0.15728334,  0.35912015,  1.16314447, -0.80147272],
         [ 0.24506448,  1.63106248,  0.59188139,  0.42563135],
         [ 0.11760464, -0.34502434, -1.79845746, -0.61258559]]]),
 array([[[ 0.49825897,  1.56629224,  1.24126046,  1.8017724 ],
         [ 1.23196204, -0.18483868, -0.43542578, -0.21057927],
         [ 0.38108351, -0.31770294, -0.70599398, -0.17534895]]]),
 array([[[ 0.57591302,  0.87155863, -0.91698176, -0.17567884],
         [ 1.63177606, -1.69967738,  0.14885536, -0.21963932],
         [-1.96420029, -2.13787323, -1.16156957,  0.04414762]]]),
 array([[[-3.15064601,  1.57556994, -0.56142087, -0.34470738],
         [-0.36405664, -1.84629627, -0.07137769,  1.01912648],
         [-0.83439953, -2.08211233,  0.20557574, -0.83159375]]])]

In [18]:
type(s0)

list

In [19]:
s0[1]

array([[[-0.15728334,  0.35912015,  1.16314447, -0.80147272],
        [ 0.24506448,  1.63106248,  0.59188139,  0.42563135],
        [ 0.11760464, -0.34502434, -1.79845746, -0.61258559]]])

In [20]:
s0[1].shape

(1, 3, 4)

In [21]:
s1=np.split (before_split, 3, axis=1)
s1

[array([[[-0.78467762,  1.32248624, -1.1323359 , -0.25169093]],
 
        [[-0.15728334,  0.35912015,  1.16314447, -0.80147272]],
 
        [[ 0.49825897,  1.56629224,  1.24126046,  1.8017724 ]],
 
        [[ 0.57591302,  0.87155863, -0.91698176, -0.17567884]],
 
        [[-3.15064601,  1.57556994, -0.56142087, -0.34470738]]]),
 array([[[-0.5731287 , -0.09421838, -1.05027001,  1.69099116]],
 
        [[ 0.24506448,  1.63106248,  0.59188139,  0.42563135]],
 
        [[ 1.23196204, -0.18483868, -0.43542578, -0.21057927]],
 
        [[ 1.63177606, -1.69967738,  0.14885536, -0.21963932]],
 
        [[-0.36405664, -1.84629627, -0.07137769,  1.01912648]]]),
 array([[[-0.56120506,  0.22738653, -1.55274232,  0.21077747]],
 
        [[ 0.11760464, -0.34502434, -1.79845746, -0.61258559]],
 
        [[ 0.38108351, -0.31770294, -0.70599398, -0.17534895]],
 
        [[-1.96420029, -2.13787323, -1.16156957,  0.04414762]],
 
        [[-0.83439953, -2.08211233,  0.20557574, -0.83159375]]])]

In [22]:
s2=np.split (before_split, 4, axis=2)
s2

[array([[[-0.78467762],
         [-0.5731287 ],
         [-0.56120506]],
 
        [[-0.15728334],
         [ 0.24506448],
         [ 0.11760464]],
 
        [[ 0.49825897],
         [ 1.23196204],
         [ 0.38108351]],
 
        [[ 0.57591302],
         [ 1.63177606],
         [-1.96420029]],
 
        [[-3.15064601],
         [-0.36405664],
         [-0.83439953]]]),
 array([[[ 1.32248624],
         [-0.09421838],
         [ 0.22738653]],
 
        [[ 0.35912015],
         [ 1.63106248],
         [-0.34502434]],
 
        [[ 1.56629224],
         [-0.18483868],
         [-0.31770294]],
 
        [[ 0.87155863],
         [-1.69967738],
         [-2.13787323]],
 
        [[ 1.57556994],
         [-1.84629627],
         [-2.08211233]]]),
 array([[[-1.1323359 ],
         [-1.05027001],
         [-1.55274232]],
 
        [[ 1.16314447],
         [ 0.59188139],
         [-1.79845746]],
 
        [[ 1.24126046],
         [-0.43542578],
         [-0.70599398]],
 
        [[-0.91698176],
 