# Adjacency Matrix

In [3]:
import numpy as np

<list>
<li>Adjacency Matrix - determine value in cell, from an adjacent cell</li>
<li>Magic Characteristics - center cell value, center cell coordinates, origin coordinates, polynomial base, </li>
<li>Magic Cube - construction and "dictionary"</li>
</list>

<h2>Structure of Adjacency Matrix</h2>

In [4]:
import numpy as np

class AdjacencyMatrix:
    """Given a cell within a magic square, an adjacency matrix calculates the value of an adjacent cell

    an adjacency matrix can also be used to calculate the value of a non-adjacent cell via 'multiplication'
    """

    def __init__(self, dimensions):
        self.dimensions = dimensions
        self.matrix = np.ones((dimensions, dimensions), dtype=np.int64)
        self.__prepare_matrix()

    def __prepare_matrix(self):
        for i in range(self.dimensions):
            for j in range(self.dimensions):
                if ((i + j) > (self.dimensions - 2)):
                    self.matrix[i,j] = 1
                else:
                    self.matrix[i,j] = -1

In [5]:
am = AdjacencyMatrix(7).matrix

In [6]:
amm = np.asmatrix(am)
amm

matrix([[-1, -1, -1, -1, -1, -1,  1],
        [-1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1,  1,  1,  1],
        [-1, -1, -1,  1,  1,  1,  1],
        [-1, -1,  1,  1,  1,  1,  1],
        [-1,  1,  1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1,  1,  1]], dtype=int64)

In [7]:
ammt = amm.T
ammt

matrix([[-1, -1, -1, -1, -1, -1,  1],
        [-1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1,  1,  1,  1],
        [-1, -1, -1,  1,  1,  1,  1],
        [-1, -1,  1,  1,  1,  1,  1],
        [-1,  1,  1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1,  1,  1]], dtype=int64)

In [8]:
ammt.I

matrix([[-0. , -0. , -0. , -0. , -0. , -0.5,  0.5],
        [ 0. ,  0. ,  0. ,  0. , -0.5,  0.5,  0. ],
        [ 0. ,  0. ,  0. , -0.5,  0.5,  0. ,  0. ],
        [ 0. ,  0. , -0.5,  0.5,  0. ,  0. ,  0. ],
        [ 0. , -0.5,  0.5,  0. ,  0. ,  0. ,  0. ],
        [-0.5,  0.5,  0. ,  0. ,  0. ,  0. , -0. ],
        [ 0.5, -0. , -0. , -0. , -0. , -0. ,  0.5]])